insert into movie (name, directorId) values ('Man with Two Brains, The', 1);
insert into movie (name, directorId) values ('Voices of Iraq', 1);
insert into movie (name, directorId) values ('Mondo Cane', 6);
insert into movie (name, directorId) values ('The Front', 2);
insert into movie (name, directorId) values ('Get Out Your Handkerchiefs (Préparez vos mouchoirs)', 5);
insert into movie (name, directorId) values ('Derek', 6);
insert into movie (name, directorId) values ('Amadeus', 4);
insert into movie (name, directorId) values ('Westward Ho', 4);
insert into movie (name, directorId) values ('In the Winter Dark', 4);
insert into movie (name, directorId) values ('Earthsea (Legend of Earthsea)', 6);
insert into movie (name, directorId) values ('Thousands Cheer', 6);
insert into movie (name, directorId) values ('Making the Earth Stand Still', 3);
insert into movie (name, directorId) values ('Täällä Pohjantähden alla II ', 8);
insert into movie (name, directorId) values ('One Last Hug', 1);
insert into movie (name, directorId) values ('Lawman', 6);
insert into movie (name, directorId) values ('Dolphin Tale', 7);
insert into movie (name, directorId) values ('Viy or Spirit of Evil (Viy)', 9);
insert into movie (name, directorId) values ('Operation ''Y'' & Other Shurik''s Adventures', 3);
insert into movie (name, directorId) values ('Prozac Nation', 3);
insert into movie (name, directorId) values ('Punisher, The', 2);
insert into movie (name, directorId) values ('Molly Maxwell', 4);
insert into movie (name, directorId) values ('Grocer''s Son, The (Fils de l''épicier, Le)', 9);
insert into movie (name, directorId) values ('Ghost Adventures', 6);
insert into movie (name, directorId) values ('Make Believe', 7);
insert into movie (name, directorId) values ('Las Vegas Story, The', 2);
insert into movie (name, directorId) values ('Open Up to Me (Kerron sinulle kaiken)', 7);
insert into movie (name, directorId) values ('Seven Angry Men', 8);
insert into movie (name, directorId) values ('As Above, So Below', 7);
insert into movie (name, directorId) values ('Mars Needs Moms', 3);
insert into movie (name, directorId) values ('Adventure of Sherlock Holmes'' Smarter Brother, The', 2);
insert into movie (name, directorId) values ('Blue', 9);
insert into movie (name, directorId) values ('Des fleurs pour Algernon', 6);
insert into movie (name, directorId) values ('Sublime', 6);
insert into movie (name, directorId) values ('Mystic Masseur, The', 4);
insert into movie (name, directorId) values ('Shenandoah', 7);
insert into movie (name, directorId) values ('Body Count', 6);
insert into movie (name, directorId) values ('The Facts of Murder', 5);
insert into movie (name, directorId) values ('White Hell of Pitz Palu, The (Die weiße Hölle vom Piz Palü) ', 5);
insert into movie (name, directorId) values ('Addams Family, The', 4);
insert into movie (name, directorId) values ('My First War', 4);
insert into movie (name, directorId) values ('House of 9', 5);
insert into movie (name, directorId) values ('Morgan Stewart''s Coming Home', 3);
insert into movie (name, directorId) values ('Incredible Hulk, The', 10);
insert into movie (name, directorId) values ('Blue Collar Comedy Tour: The Movie', 1);
insert into movie (name, directorId) values ('Bad Company', 9);
insert into movie (name, directorId) values ('Coming to America', 5);
insert into movie (name, directorId) values ('Ed', 3);
insert into movie (name, directorId) values ('December Boys', 4);
insert into movie (name, directorId) values ('Upstairs and Downstairs', 7);
insert into movie (name, directorId) values ('Steel', 2);
