insert into movie ("name", "directorId") values ('Charlie Chan in Rio', 10);
insert into movie ("name", "directorId") values ('Edge of Darkness', 5);
insert into movie ("name", "directorId") values ('Mann tut was Mann kann', 8);
insert into movie ("name", "directorId") values ('Post Mortem', 4);
insert into movie ("name", "directorId") values ('Taifu Club (Taifû kurabu)', 5);
insert into movie ("name", "directorId") values ('Yellow Handkerchief, The', 10);
insert into movie ("name", "directorId") values ('Koti-ikävä', 7);
insert into movie ("name", "directorId") values ('Metro Manila', 10);
insert into movie ("name", "directorId") values ('Gypsy 83', 9);
insert into movie ("name", "directorId") values ('Full Monty, The', 4);
insert into movie ("name", "directorId") values ('Antares', 9);
insert into movie ("name", "directorId") values ('Story of Maths, The', 3);
insert into movie ("name", "directorId") values ('Have Dreams, Will Travel', 6);
insert into movie ("name", "directorId") values ('Schooled: The Price of College Sports ', 1);
insert into movie ("name", "directorId") values ('Ultraviolet', 10);
insert into movie ("name", "directorId") values ('Charlie Chan in Panama', 7);
insert into movie ("name", "directorId") values ('Replicant', 1);
insert into movie ("name", "directorId") values ('Appleseed Alpha', 1);
insert into movie ("name", "directorId") values ('Marie and Bruce', 5);
insert into movie ("name", "directorId") values ('Quicksilver', 5);
insert into movie ("name", "directorId") values ('Guest, The', 9);
insert into movie ("name", "directorId") values ('Free Money', 10);
insert into movie ("name", "directorId") values ('Premature Burial, The', 1);
insert into movie ("name", "directorId") values ('Cheech & Chong''s Nice Dreams', 6);
insert into movie ("name", "directorId") values ('Svampe', 4);
insert into movie ("name", "directorId") values ('King Solomon''s Mines', 9);
insert into movie ("name", "directorId") values ('CB4 - The Movie', 7);
insert into movie ("name", "directorId") values ('Jurassic Park', 3);
insert into movie ("name", "directorId") values ('Man Made Monster', 10);
insert into movie ("name", "directorId") values ('Ernest Film Festival, The', 3);
insert into movie ("name", "directorId") values ('Anton Chekhov''s The Duel', 6);
insert into movie ("name", "directorId") values ('Print the Legend', 6);
insert into movie ("name", "directorId") values ('Snowball Express', 3);
insert into movie ("name", "directorId") values ('Boris Godunov', 6);
insert into movie ("name", "directorId") values ('Home Alone 2: Lost in New York', 9);
insert into movie ("name", "directorId") values ('Marilyn Hotchkiss'' Ballroom Dancing & Charm School', 4);
insert into movie ("name", "directorId") values ('With Honors', 5);
insert into movie ("name", "directorId") values ('God is Great, I''m Not (Dieu est grand, je suis toute petite)', 8);
insert into movie ("name", "directorId") values ('Ballad of the Little Soldier (Ballade vom kleinen Soldaten)', 4);
insert into movie ("name", "directorId") values ('Alien Escape', 4);
insert into movie ("name", "directorId") values ('Without Warning (a.k.a. Alien Warning) (a.k.a. It Came Without Warning)', 9);
insert into movie ("name", "directorId") values ('Supercop 2 (Project S) (Chao ji ji hua)', 7);
insert into movie ("name", "directorId") values ('I Killed My Mother (J''ai tué ma mère)', 3);
insert into movie ("name", "directorId") values ('Chasing Ghosts: Beyond the Arcade ', 3);
insert into movie ("name", "directorId") values ('Darker Than Night', 8);
insert into movie ("name", "directorId") values ('Vanishing, The', 6);
insert into movie ("name", "directorId") values ('Winter Solstice', 1);
insert into movie ("name", "directorId") values ('The Sea Chase', 1);
insert into movie ("name", "directorId") values ('Red and the White, The (Csillagosok, katonák)', 4);
insert into movie ("name", "directorId") values ('Hamlet', 3);
