insert into movie ("id", "name", "directorId") values (1, 'That''s Black Entertainment', 4);
insert into movie ("id", "name", "directorId") values (2, 'Honor Among Thieves (Adieu l''ami) (Farewell, Friend)', 6);
insert into movie ("id", "name", "directorId") values (3, 'Quiet Duel, The (Shizukanaru ketto)', 6);
insert into movie ("id", "name", "directorId") values (4, 'Tammy', 7);
insert into movie ("id", "name", "directorId") values (5, 'Repatriation', 5);
insert into movie ("id", "name", "directorId") values (6, 'Dark Woods (Villmark)', 4);
insert into movie ("id", "name", "directorId") values (7, 'Blithe Spirit', 8);
insert into movie ("id", "name", "directorId") values (8, 'Lethal Weapon 3', 2);
insert into movie ("id", "name", "directorId") values (9, 'Twice in a Lifetime', 6);
insert into movie ("id", "name", "directorId") values (10, 'Dawn of the Dead', 1);
insert into movie ("id", "name", "directorId") values (11, 'A Follower for Emily', 9);
insert into movie ("id", "name", "directorId") values (12, 'Scent of Green Papaya, The (Mùi du du xhan - L''odeur de la papaye verte)', 6);
insert into movie ("id", "name", "directorId") values (13, 'Author! Author!', 1);
insert into movie ("id", "name", "directorId") values (14, 'Victor and the Secret of Crocodile Mansion', 1);
insert into movie ("id", "name", "directorId") values (15, 'Go Go Tales', 6);
insert into movie ("id", "name", "directorId") values (16, 'Dancing Lady', 10);
insert into movie ("id", "name", "directorId") values (17, 'Winnebago Man', 7);
insert into movie ("id", "name", "directorId") values (18, 'Teen Spirit', 4);
insert into movie ("id", "name", "directorId") values (19, 'Taxi for Tobruk', 6);
insert into movie ("id", "name", "directorId") values (20, 'Good Neighbor Sam', 6);
insert into movie ("id", "name", "directorId") values (21, 'Beyond Therapy', 1);
insert into movie ("id", "name", "directorId") values (22, 'Fire Down Below', 3);
insert into movie ("id", "name", "directorId") values (23, 'From Up on Poppy Hill (Kokuriko-zaka kara)', 7);
insert into movie ("id", "name", "directorId") values (24, 'Proposal, The', 9);
insert into movie ("id", "name", "directorId") values (25, 'Deep End', 6);
insert into movie ("id", "name", "directorId") values (26, 'Fast and the Furious: Tokyo Drift, The (Fast and the Furious 3, The)', 9);
insert into movie ("id", "name", "directorId") values (27, 'Sin City', 8);
insert into movie ("id", "name", "directorId") values (28, 'Go-Getter, The', 10);
insert into movie ("id", "name", "directorId") values (29, 'Dealing: Or the Berkeley-to-Boston Forty-Brick Lost-Bag Blues', 4);
insert into movie ("id", "name", "directorId") values (30, 'Warning from Space (Uchûjin Tôkyô ni arawaru)', 10);
insert into movie ("id", "name", "directorId") values (31, 'Somewhere Under the Broad Sky', 9);
insert into movie ("id", "name", "directorId") values (32, 'Harley Davidson and the Marlboro Man', 5);
insert into movie ("id", "name", "directorId") values (33, 'Man Vanishes, A (Ningen Johatsu)', 2);
insert into movie ("id", "name", "directorId") values (34, 'Living Out Loud', 10);
insert into movie ("id", "name", "directorId") values (35, 'And So It Is', 6);
insert into movie ("id", "name", "directorId") values (36, 'Gentlemen Don''t Eat Poets (Grotesque, The)', 3);
insert into movie ("id", "name", "directorId") values (37, 'Moonlight Mile', 10);
insert into movie ("id", "name", "directorId") values (38, 'Way of the Gun, The', 1);
insert into movie ("id", "name", "directorId") values (39, 'Maybe, Maybe Not (Bewegte Mann, Der)', 7);
insert into movie ("id", "name", "directorId") values (40, 'Ninja Assassin', 6);
insert into movie ("id", "name", "directorId") values (41, 'Beach Party', 3);
insert into movie ("id", "name", "directorId") values (42, 'Start the Revolution Without Me', 7);
insert into movie ("id", "name", "directorId") values (43, 'Gambit', 3);
insert into movie ("id", "name", "directorId") values (44, 'Pariah', 3);
insert into movie ("id", "name", "directorId") values (45, 'Rain', 2);
insert into movie ("id", "name", "directorId") values (46, 'Dunwich Horror, The', 4);
insert into movie ("id", "name", "directorId") values (47, 'Cotton Club, The', 4);
insert into movie ("id", "name", "directorId") values (48, 'Girl on a Motorcycle, The', 5);
insert into movie ("id", "name", "directorId") values (49, 'Need for Speed', 5);
insert into movie ("id", "name", "directorId") values (50, 'Jim Jefferies: BARE', 10);
